# List of all valid genres on IMDb.
GENRES = [
    "action",
    "adventure",
    "animation",
    "biography",
    "comedy",
    "crime",
    "drama",
    "family",
    "fantasy",
    "film-Noir",
    "history",
    "horror",
    "music",
    "musical",
    "mystery",
    "romance",
    "sci-Fi",
    "sport",
    "thriller",
    "war",
    "western",
]
